function appendToParagraph(paragraph , data)
	{
	var para = document.createElement("P");                       
	var t = document.createTextNode(data);    
	para.appendChild(t);  
	document.getElementById(paragraph).appendChild(para);
	}
	
function getFields()
	{
	//fields defined in this function so can add/remove fields as and when we like
	//form generated by generateForm
	
	var username=new Object();
	var addressLine1=new Object();
	var addressLine2=new Object();
	var addressLine3=new Object();
	var telephone=new Object();
	var email=new Object();
	var comments=new Object();
	
	username.Id = "username";
	username.label = "Name";
	
	addressLine1.Id = "addressLine1";
	addressLine1.label = "Address";
	
	//No Label for these
	addressLine2.Id = "addressLine2";	
	addressLine3.Id = "addressLine3";
	
	telephone.Id = "telephone";
	telephone.label = "Telephone";
	
	email.Id = "email";
	email.label = "Email Address";
	
	comments.Id = "comments";
	comments.label = "Comments";
	
	var fields = [ username , addressLine1 , addressLine2 , addressLine3 , telephone , email , comments ] ;
	
	return fields;	
	}

function generateForm()
	{
		//dynamically add fields to form
		//may be better to have it generalised so can add fields to any form, without knowing its name.
		
		//also, bit of a HACK for the comments field: might be better if could add information about what input type required to fields
		
		var fields = getFields();
		
		for (i=0 ; i < fields.length; i++)
			{
			var label = document.createTextNode(fields[i].label + " :");
			var input = document.createElement("INPUT");
			
			if (fields[i].Id != "comments")
				{
				input.setAttribute("type", "text");
				input.setAttribute("id", fields[i].Id);
				}
			
			else
				{
				input = document.createElement("TEXTAREA");
				input.setAttribute("id", fields[i].Id);				
				input.setAttribute("rows" , 5);
				input.setAttribute("cols" , 80);
				
				}

			document.getElementById("comments_form").appendChild(label);
			document.getElementById("comments_form").appendChild(input);
			
			var br = document.createElement("br");
			document.getElementById("comments_form").appendChild(br);

			}		
	}
	
function submit_Details()
	{
	
	// Just a quick function to add comments from form
	// No validation just yet
		
		var fields = getFields();
		
		for (i=0 ; i < fields.length; i++)
			{
			localStorage.setItem(fields[i].Id , document.getElementById(fields[i].Id).value);	
			}	
		//set New_Comments variable to true to tell updateComments to load the latest comment	
		localStorage.setItem("New_Comments" , "true");
		window.location = "comments.html";
	}
	
function resetComments()
	{
		var confirm = prompt("Are you SURE you want to do this?\nIf so, type YES.\nTyping ANYTHING else will leave comments as they are");
		
		if ((confirm != null) && (confirm != ""))
			{
			confirm=confirm.toUpperCase();
			confirm=confirm.replace(/\s+/g , "");
		
			if (confirm === "YES")
				{
				localStorage.setItem("previousComments" , "");
				document.getElementById("Latest_Comments").innerHTML = "";
				}
			}
	
		//set New_Comments variable to false to tell updateComments NOT to load the latest comment
		//will still be in localStorage until overwritten
		localStorage.setItem("New_Comments" , "false");
		
		window.location = "comments.html";
	}
	
function updateComments()
	{
		var previousComments = localStorage.getItem("previousComments");
		
		if ((previousComments != null) && (previousComments != ""))
			{document.getElementById("Latest_Comments").innerHTML = previousComments;}
		
		//see comments above in resetComments and submit_Details
		if (localStorage.getItem("New_Comments") === "true")
			{
			
			var fields = getFields();
			for (i=0 ; i < fields.length; i++)		
				{
				var nextLine = localStorage.getItem(fields[i].Id);
				appendToParagraph("Latest_Comments" , nextLine);
				}	
		
			nextLine = "Date: " + Date();
			appendToParagraph("Latest_Comments" , nextLine);
			nextLine = "=============================================================================";
			appendToParagraph("Latest_Comments" , nextLine);
		
			localStorage.setItem("previousComments" , document.getElementById("Latest_Comments").innerHTML);
			localStorage.setItem("New_Comments" , "false");
			}

	}